const keyCodeByKey = { 
    "1": {key:"1",keyCode:"49", neighbors: ["2", "A"]},
    "2": {key:"2",keyCode:"50", neighbors: ["1", "3", "A", "Z"]},
    "3": {key:"3",keyCode:"51", neighbors: ["2", "4", "Z", "E"]},
    "4": {key:"4",keyCode:"52", neighbors: ["3", "5", "E", "R"]},
    "5": {key:"5",keyCode:"53", neighbors: ["4", "6", "R", "T"]},
    "6": {key:"6",keyCode:"54", neighbors: ["5", "7", "T", "Y"]},
    "7": {key:"7",keyCode:"55", neighbors: ["6", "8", "Y", "U"]},
    "8": {key:"8",keyCode:"56", neighbors: ["7", "9", "U", "I"]},
    "9": {key:"9",keyCode:"57", neighbors: ["8", "0", "I", "O"]},
    "0": {key:"0",keyCode:"48", neighbors: ["9", "°", "O", "P"]},
    "°": {key:"°",keyCode:"219", neighbors: ["0", "+", "P", "¨"]},
    "+": {key:"+",keyCode:"187", neighbors: ["°", "¨", "£"]},
    "A": {key:"A",keyCode:"65", neighbors: ["1", "2", "Z", "Q"]},
    "Z": {key:"Z",keyCode:"90", neighbors: ["2", "3", "A", "E", "Q", "S"]},
    "E": {key:"E",keyCode:"69", neighbors: ["3", "4", "Z", "R", "S", "D"]},
    "R": {key:"R",keyCode:"82", neighbors: ["4", "5", "E", "T", "D", "F"]},
    "T": {key:"T",keyCode:"84", neighbors: ["5", "6", "R", "Y", "F", "G"]},
    "Y": {key:"Y",keyCode:"88", neighbors: ["6", "7", "T", "U", "G", "H"]},
    "U": {key:"U",keyCode:"85", neighbors: ["7", "8", "Y", "I", "H", "J"]},
    "I": {key:"I",keyCode:"73", neighbors: ["8", "9", "U", "O", "J", "K"]},
    "O": {key:"O",keyCode:"79", neighbors: ["9", "0", "I", "P", "K", "L"]},
    "P": {key:"P",keyCode:"80", neighbors: ["0", "°", "O", "¨", "L", "M"]},
    "¨": {key:"¨",keyCode:"221", neighbors: ["°", "+", "P", "£", "M", "%"]},
    "£": {key:"£",keyCode:"186", neighbors: ["+", "¨", "%", "µ"]},
    "Q": {key:"Q",keyCode:"81", neighbors: ["A", "Z", "S",">", "W"]},
    "S": {key:"S",keyCode:"83", neighbors: ["Z", "E", "Q","D", "W", "X"]},
    "D": {key:"D",keyCode:"68", neighbors: ["E", "R", "S","F", "X", "C"]},
    "F": {key:"F",keyCode:"70", neighbors: ["R", "T", "D","G", "C", "V"]},
    "G": {key:"G",keyCode:"71", neighbors: ["T", "Y", "F","H", "V", "B"]},
    "H": {key:"H",keyCode:"72", neighbors: ["Y", "U", "G","J", "B", "N"]},
    "J": {key:"J",keyCode:"74", neighbors: ["U", "I", "H","K", "N", "?"]},
    "K": {key:"K",keyCode:"75", neighbors: ["I", "O", "J","L", "?", "."]},
    "L": {key:"L",keyCode:"76", neighbors: ["O", "P", "K","M", ".", "/"]},
    "M": {key:"M",keyCode:"77", neighbors: ["P", "¨", "L","%", "/", "§"]},
    "%": {key:"%",keyCode:"192", neighbors: ["¨","£", "M","µ", "§" ]},
    "µ": {key:"µ",keyCode:"220", neighbors: ["£", "%",]},
    ">": {key:">",keyCode:"226", neighbors: ["Q", "W"]},
    "W": {key:"W",keyCode:"87", neighbors: ["Q", "S", ">", "X"]},
    "X": {key:"X",keyCode:"88", neighbors: ["S", "D", "W", "C"]},
    "C": {key:"C",keyCode:"67", neighbors: ["D", "F", "X", "V"]},
    "V": {key:"V",keyCode:"86", neighbors: ["F", "G", "C", "B"]},
    "B": {key:"B",keyCode:"66", neighbors: ["G", "H", "V", "N"]},
    "N": {key:"N",keyCode:"78", neighbors: ["H", "J", "B", "?"]},
    "?": {key:"?",keyCode:"188", neighbors: ["J", "K", "N", "."]},
    ".": {key:".",keyCode:"190", neighbors: ["K", "L", "?", "/"]},
    "/": {key:"/",keyCode:"191", neighbors: ["L", "M", ".", "§"]},
    "§": {key:"§",keyCode:"223", neighbors: ["M", "%", "/"]}
}


const keyBykeyCode = { 
    "49": {key:"1",keyCode:"49", neighbors: ["2", "A"]},
    "50": {key:"2",keyCode:"50", neighbors: ["1", "3", "A", "Z"]},
    "51": {key:"3",keyCode:"51", neighbors: ["2", "4", "Z", "E"]},
    "52": {key:"4",keyCode:"52", neighbors: ["3", "5", "E", "R"]},
    "53": {key:"5",keyCode:"53", neighbors: ["4", "6", "R", "T"]},
    "54": {key:"6",keyCode:"54", neighbors: ["5", "7", "T", "Y"]},
    "55": {key:"7",keyCode:"55", neighbors: ["6", "8", "Y", "U"]},
    "56": {key:"8",keyCode:"56", neighbors: ["7", "9", "U", "I"]},
    "57": {key:"9",keyCode:"57", neighbors: ["8", "0", "I", "O"]},
    "48": {key:"0",keyCode:"48", neighbors: ["9", "°", "O", "P"]},
    "219": {key:"°",keyCode:"219", neighbors: ["0", "+", "P", "¨"]},
    "187": {key:"+",keyCode:"187", neighbors: ["°", "¨", "£"]},
    "65": {key:"A",keyCode:"65", neighbors: ["1", "2", "Z", "Q"]},
    "90": {key:"Z",keyCode:"90", neighbors: ["2", "3", "A", "E", "Q", "S"]},
    "69": {key:"E",keyCode:"69", neighbors: ["3", "4", "Z", "R", "S", "D"]},
    "82": {key:"R",keyCode:"82", neighbors: ["4", "5", "E", "T", "D", "F"]},
    "84": {key:"T",keyCode:"84", neighbors: ["5", "6", "R", "Y", "F", "G"]},
    "88": {key:"Y",keyCode:"88", neighbors: ["6", "7", "T", "U", "G", "H"]},
    "85": {key:"U",keyCode:"85", neighbors: ["7", "8", "Y", "I", "H", "J"]},
    "73": {key:"I",keyCode:"73", neighbors: ["8", "9", "U", "O", "J", "K"]},
    "79": {key:"O",keyCode:"79", neighbors: ["9", "0", "I", "P", "K", "L"]},
    "80": {key:"P",keyCode:"80", neighbors: ["0", "°", "O", "¨", "L", "M"]},
    "221": {key:"¨",keyCode:"221", neighbors: ["°", "+", "P", "£", "M", "%"]},
    "186": {key:"£",keyCode:"186", neighbors: ["+", "¨", "%", "µ"]},
    "81": {key:"Q",keyCode:"81", neighbors: ["A", "Z", "S",">", "W"]},
    "83": {key:"S",keyCode:"83", neighbors: ["Z", "E", "Q","D", "W", "X"]},
    "68": {key:"D",keyCode:"68", neighbors: ["E", "R", "S","F", "X", "C"]},
    "70": {key:"F",keyCode:"70", neighbors: ["R", "T", "D","G", "C", "V"]},
    "71": {key:"G",keyCode:"71", neighbors: ["T", "Y", "F","H", "V", "B"]},
    "72": {key:"H",keyCode:"72", neighbors: ["Y", "U", "G","J", "B", "N"]},
    "74": {key:"J",keyCode:"74", neighbors: ["U", "I", "H","K", "N", "?"]},
    "75": {key:"K",keyCode:"75", neighbors: ["I", "O", "J","L", "?", "."]},
    "76": {key:"L",keyCode:"76", neighbors: ["O", "P", "K","M", ".", "/"]},
    "77": {key:"M",keyCode:"77", neighbors: ["P", "¨", "L","%", "/", "§"]},
    "192": {key:"%",keyCode:"192", neighbors: ["¨","£", "M","µ", "§" ]},
    "220": {key:"µ",keyCode:"220", neighbors: ["£", "%",]},
    "226": {key:">",keyCode:"226", neighbors: ["Q", "W"]},
    "87": {key:"W",keyCode:"87", neighbors: ["Q", "S", ">", "X"]},
    "88": {key:"X",keyCode:"88", neighbors: ["S", "D", "W", "C"]},
    "67": {key:"C",keyCode:"67", neighbors: ["D", "F", "X", "V"]},
    "86": {key:"V",keyCode:"86", neighbors: ["F", "G", "C", "B"]},
    "66": {key:"B",keyCode:"66", neighbors: ["G", "H", "V", "N"]},
    "78": {key:"N",keyCode:"78", neighbors: ["H", "J", "B", "?"]},
    "188": {key:"?",keyCode:"188", neighbors: ["J", "K", "N", "."]},
    "190": {key:".",keyCode:"190", neighbors: ["K", "L", "?", "/"]},
    "191": {key:"/",keyCode:"191", neighbors: ["L", "M", ".", "§"]},
    "223": {key:"§",keyCode:"223", neighbors: ["M", "%", "/"]}
}